services:
  kunooz:
    build: .
    restart: always
    volumes:
      - ./:/usr/src/app
      - django-folder:/s3files
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: kunooz-db
      DB_PORT: 5432
    depends_on:
      - kunooz-db

  kunooz-db:
    image: postgres:17
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_MAX_CONNECTIONS: 2000
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    networks:
      - db-net

volumes:
  postgresql_data:
  django-folder: