services:
  kunooz:
    build: .
    restart: always
    volumes:
      - ./:/usr/src/app
      - django-folder:/s3files
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: kunooz-db  # هنا استخدم اسم الخدمة مباشرة
      DB_PORT: 5432
    depends_on:
      - kunooz-db

  kunooz-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  django-folder: